joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  
  
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_1_joint
  pid: {p: 3000, i: 0.00, d:  0.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_2_joint
  pid: {p: 20000, i: 0.00, d:  0.0}
  
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_3_joint
  pid: {p: 4000, i: 0.00, d:  0.0}
  
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_4_joint
  pid: {p: 8000, i: 0.00, d:  0.0}
  
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_5_joint
  pid: {p: 4000, i: 0.00, d:  0.0}
  
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_6_joint
  pid: {p: 6000, i: 0.00, d:  0.0}
  
joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_7_joint
  pid: {p: 4000, i: 0.00, d:  0.0}
